### ISSUE TITLE
Cannot run 'go get github.com/bitmovin/bitmovin-go'

### ISSUE THREAD

**Issue by reeeeeeeeeeee** [bitmovin/bitmovin-go#14]
go get github.com/bitmovin/bitmovin-go
can't load package: package github.com/bitmovin/bitmovin-go: no buildable Go source files in /Users/tomorier/go/src/github.com/bitmovin/bitmovin-go

**Comment by Tigraine** [comment]
Hi @reeeeeeeeeeee this is normal for a library that has no `main()` method.
The Bitmovin Go Client is just a library you have to have on your `GOPATH` in order to import it into your own projects.
`go get` downloaded the code to `/Users/tomorier/go/src/github.com/bitmovin/bitmovin-go` from where you can now use it inside your code.

You can now create your own project and import the client like this:

```
import (
  "github.com/bitmovin/bitmovin-go/bitmovin"
  "github.com/bitmovin/bitmovin-go/bitmovintypes"
  "github.com/bitmovin/bitmovin-go/models"
  "github.com/bitmovin/bitmovin-go/services"
)
```

For more usage examples see the [examples folder](https://github.com/bitmovin/bitmovin-go/tree/master/examples) in the repository.
